  $ cat > dune-project << EOF
  > (lang dune 3.10)
  > 
  > (package
  >  (name l))
  > EOF

  $ cat > dune << EOF
  > (library
  >  (public_name l))
  > EOF

  $ cat > l.ml << EOF
  > module M = struct
  >   type t = int
  > end
  > EOF

  $ list_html () {
  >   find _build/default/_doc/_html -name '*.html' | sort
  > }
  $ list_json () {
  >   find _build/default/_doc/_json -name '*.html.json' | sort
  > }

json documentation is generated into its own _json tree:
  $ dune build @doc-json
  $ list_json
  _build/default/_doc/_json/index.html.json
  _build/default/_doc/_json/l/L/M/index.html.json
  _build/default/_doc/_json/l/L/index.html.json
  _build/default/_doc/_json/l/index.html.json

The toplevel index is generated by dune itself:

  $ cat _build/default/_doc/_json/index.html.json
  {"packages":[{"name":"l","version":null,"link":"l/index.html"}]}

@doc generates html into the _html tree:

  $ dune build @doc
  $ list_html
  _build/default/_doc/_html/index.html
  _build/default/_doc/_html/l/L/M/index.html
  _build/default/_doc/_html/l/L/index.html
  _build/default/_doc/_html/l/index.html
